Review PR
FlockOfBirds/mendix-widget-build-script pull request #1
Opened 2017-08-07 07:59 UTC by Andries-Smit

2017-08-07 15:25 UTC, edwinmp requested changes
There you go. Sorry it took a while.

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +For the purpose oft continues integration and testing.
For the purpose **of continuous** integration ...

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +These script can checkout a Mendix project, update the latest widget, build, upload and start the project to cloud node.
... and start the project **on a cloud** node

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +After these script integrations test could be run on the node.
After these **scripts, integration tests** could be run ...

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +  - MX_APP_NAME=texteditorwidget
`MX_APP_NAME=your-app-name`

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +  - MX_PROJECT_ID=8648ccda-9281-4768-abb2-8ce61a80e2f1
`MX_PROJECT_ID=your-project-id`

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +  - MX_USER=ci@example.org
`MX_USER=your-mx-user-email`

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +  - secure: [secret]
Can remove this. Slow users (like myself) can assume it's part of the code as it is :)

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +Create your own secrets for your MX_API_KEY and MX_PASSWORD via travis CLI
Generate the encrypted values for your MX_API_KEY and MX_PASSWORD via Travis CLI. They'll be appended as secrets to your .travis.yml, with the rest of your global variables.

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +Create your own secrets for your MX_API_KEY and MX_PASSWORD via travis CLI
Perhaps add some links related to installing Travis CLI.

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +Note: for security reason it is advisable to create an CI user that can only access the testing repositories.
Note: for security **reasons,** it is advisable to create **a CI** user that

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +Travis CLI: https://github.com/travis-ci/travis.rb
Move this higher.

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +The CLI can help you setup the an github token
In my experience, this can only be done before the deploy section is even added. Won't generate with one existing. I suggest moving this to line 33, then instructions to add any values the CLI doesn't auto include e.g tags: true, file_glob, skip_cleanup.

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +!! **Important** !! Add this file to your git ignore, as the password and key are not encrypted they should never commit into a public repository
... they should `never be committed` into a public

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +4) Add to the npm `package.json` the "widgetName" and the script the required scripts for deployment
... `"widgetName" and the required scripts` for deployment

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +    "pretest": "<build script, output the widget into 'dist/<version>'>",
Ran into a problem with the existing pretest script. It calls `npm build`, but the specified scripts where `build:dev` & `build:prod`.

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +6) Add the awesome badges to the `readme.md` to show build status
`README.md`

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +7) Commit the changes int your repo (Except the local config)
... changes `into your` repo

2017-08-07 15:25 UTC, edwinmp commented on readme.md
> +Testings can be done with copy and configure `localSettings.js` in the project root and run:
Something's wrong with this sentence... not sure how to rephrase it.

2017-08-07 15:25 UTC, edwinmp commented on src/DeployMxApp.ts
> +const branchName = settings.branchName;
Consider destructuring `settings` instead.

2017-08-07 15:25 UTC, edwinmp commented on src/DeployMxApp.ts
> +                return;
Blank line before.

2017-08-07 15:25 UTC, edwinmp commented on src/DeployMxApp.ts
> +            const nextRev = branch.LatestRevisionNumber.toString();
You've been pretty consistent with using full names... `nextRevisionNumber`.

2017-08-07 15:25 UTC, edwinmp commented on src/DeployMxApp.ts
> +                return;
Blank line before.

2017-08-07 15:25 UTC, edwinmp commented on src/DeployMxApp.ts
> +                await deploy.waitForSandboxStart(appName, 600);
Comment says 60 secs but specified 600

2017-08-07 15:25 UTC, edwinmp commented on src/DeployMxApp.ts
> +                console.log("Stop app:", appName, environment);
Consider moving `console.log`s to the actual functions. Cleaner...

2017-08-07 15:25 UTC, edwinmp commented on src/Settings.ts
> +export interface Settings extends MinimalSettings {
Blank line before.

2017-08-07 15:25 UTC, edwinmp commented on src/Settings.ts
> +export type Partial<T> = {
This is already part of typescript 2.2 I think. Don't need to recreate it.

2017-08-07 15:25 UTC, edwinmp commented on src/Settings.ts
> +    let settings: PartialSettings = defaultSettings;
Type is inferred from assignment.

2017-08-07 15:25 UTC, edwinmp commented on src/Settings.ts
> +    return <Settings>settings;
Blank line before.

2017-08-07 15:25 UTC, edwinmp commented on src/Settings.ts
> +    return <Settings>settings;
This kind of casting is not recommended. Use `as Settings`.

2017-08-07 15:25 UTC, edwinmp commented on src/Settings.ts
> +export type PartialSettings = Partial<Settings>;
**Prefer** it stays in it's original form `Partial<Settings>` and export only Settings... difference is just two angle brackets :)

2017-08-07 15:25 UTC, edwinmp commented on src/localSettings.ts
> +// NEVER EVER COMMIT THIS FILE!!
Damn, the way this message screams... Makes u think the world will explode if you EVER commit this file... :)

2017-08-07 15:25 UTC, edwinmp commented on src/services/Service.ts
> +export function postRequest<T>(opts: any) {
A lot of similar code in here. `Get`, `Post`, `Delete `can be handled in one function, and the `any` usage reduced with generics.

2017-08-07 15:25 UTC, edwinmp commented on src/services/BuildService.ts
> +                    return;
Blank line before

2017-08-07 15:25 UTC, edwinmp commented on src/services/BuildService.ts
> +                            reject("Build status is 'Failed' check the 'Latest build output' on https://cloud.home.mendix.com DEPLOY > Environments" );
**Build Failed. Check the latest** ....

2017-08-07 15:25 UTC, edwinmp commented on src/services/DeploymentService.ts
> +export type EnvironmentMode = "Sandbox" | "Test" | "Acceptance" | "Production";
If the type definitions are becoming too many, may need to extract them into their own .d.ts

2017-08-07 18:08 UTC, Andries-Smit commented on src/Settings.ts
> +export type PartialSettings = Partial<Settings>;
Sharp

2017-08-07 18:09 UTC, Andries-Smit commented on src/Settings.ts
> +    return <Settings>settings;
Looks nice indeed!

2017-08-07 18:15 UTC, Andries-Smit commented on src/services/DeploymentService.ts
> +export type EnvironmentMode = "Sandbox" | "Test" | "Acceptance" | "Production";
We could, how should we name it?

2017-08-07 18:16 UTC, Andries-Smit commented on readme.md
> +For the purpose oft continues integration and testing.
Done

2017-08-07 18:16 UTC, Andries-Smit commented on readme.md
> +These script can checkout a Mendix project, update the latest widget, build, upload and start the project to cloud node.
Done

2017-08-07 18:16 UTC, Andries-Smit commented on readme.md
> +After these script integrations test could be run on the node.
Done

2017-08-07 18:16 UTC, Andries-Smit commented on readme.md
> +  - MX_APP_NAME=texteditorwidget
Done

2017-08-07 18:16 UTC, Andries-Smit commented on readme.md
> +  - MX_PROJECT_ID=8648ccda-9281-4768-abb2-8ce61a80e2f1
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +Create your own secrets for your MX_API_KEY and MX_PASSWORD via travis CLI
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +  - secure: [secret]
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +  - MX_USER=ci@example.org
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +4) Add to the npm `package.json` the "widgetName" and the script the required scripts for deployment
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +!! **Important** !! Add this file to your git ignore, as the password and key are not encrypted they should never commit into a public repository
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +The CLI can help you setup the an github token
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +7) Commit the changes int your repo (Except the local config)
Done

2017-08-07 18:38 UTC, Andries-Smit commented on readme.md
> +6) Add the awesome badges to the `readme.md` to show build status
Done

2017-08-07 18:39 UTC, Andries-Smit commented on readme.md
> +    "pretest": "<build script, output the widget into 'dist/<version>'>",
Seen the issue, fixed it on the other branch.

2017-08-07 18:39 UTC, Andries-Smit commented on readme.md
> +Testings can be done with copy and configure `localSettings.js` in the project root and run:
Done

2017-08-07 18:39 UTC, Andries-Smit commented on src/DeployMxApp.ts
> +const branchName = settings.branchName;
Done

2017-08-07 18:39 UTC, Andries-Smit commented on src/DeployMxApp.ts
> +                return;
Done

2017-08-07 18:39 UTC, Andries-Smit commented on src/DeployMxApp.ts
> +                return;
Done

2017-08-07 18:40 UTC, Andries-Smit commented on src/DeployMxApp.ts
> +                await deploy.waitForSandboxStart(appName, 600);
Comment as unclear, did updated it. Transport starts after 60 second, 600 is the timeout... before giving up the waiting the start up to finish.

2017-08-07 18:41 UTC, Andries-Smit commented on src/Settings.ts
> +export interface Settings extends MinimalSettings {
Done

2017-08-07 18:41 UTC, Andries-Smit commented on src/Settings.ts
> +export type PartialSettings = Partial<Settings>;
Done

2017-08-07 18:41 UTC, Andries-Smit commented on src/Settings.ts
> +    let settings: PartialSettings = defaultSettings;
Done

2017-08-07 18:41 UTC, Andries-Smit commented on src/Settings.ts
> +    return <Settings>settings;
Done

2017-08-07 18:44 UTC, Andries-Smit commented on src/localSettings.ts
> +// NEVER EVER COMMIT THIS FILE!!
YUP! It will cost life time chapati if you do it...  :no_mouth:

2017-08-07 18:44 UTC, Andries-Smit commented on src/services/Service.ts
> +export function postRequest<T>(opts: any) {
Please show me how...

2017-08-07 18:45 UTC, Andries-Smit commented on src/services/BuildService.ts
> +                    return;
Done

2017-08-07 18:45 UTC, Andries-Smit commented on src/services/BuildService.ts
> +                            reject("Build status is 'Failed' check the 'Latest build output' on https://cloud.home.mendix.com DEPLOY > Environments" );
Done

2017-08-07 19:26 UTC, Andries-Smit commented on src/DeployMxApp.ts
> +                console.log("Stop app:", appName, environment);
That is a lot of work... though it cleans up the code big time..... Done...

2017-08-09 17:09 UTC, Andries-Smit commented on readme.md
> +Note: for security reason it is advisable to create an CI user that can only access the testing repositories.
Done

2017-08-09 17:10 UTC, Andries-Smit commented on readme.md
> +Travis CLI: https://github.com/travis-ci/travis.rb
Done

2017-08-09 17:10 UTC, Andries-Smit commented on src/DeployMxApp.ts
> +            const nextRev = branch.LatestRevisionNumber.toString();
Done

2017-08-09 17:10 UTC, Andries-Smit commented on src/Settings.ts
> +export type Partial<T> = {
Done

2018-12-11 09:05 UTC, Andries-Smit commented
Old PR

2018-12-11 09:05 UTC, closed without merging